name: Importer
version: 1.0.0
description: Importer Plugin
author:
  name: Sergey Romanenko
  email: awilum@yandex.ru
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/importer
bugs: https://github.com/flextype-plugins/importer/issues
license: MIT
